import nodemailer from 'nodemailer';
import path from 'path';    
import dotenv from 'dotenv';        

// Email Configuration (SMTP or Service like Gmail, SendGrid)
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    type: "OAuth2",
    user: process.env.EMAIL_USERNAME,
    clientId: process.env.GOOGLE_CLIENT_ID,
    clientSecret: process.env.GOOGLE_CLIENT_SECRET,
  },
});
// The sendEmail function to send the email
export const sendEmail = async () => {
  dotenv.config();

  // Email options
  const mailOptions = {
    from: process.env.EMAIL_USERNAME,
    to: process.env.RECIPIENT_EMAIL,  // Add the recipient's email address
    subject: 'Playwright Test Results & Screenshots',
    text: 'The Playwright automation tests are completed. Please find the attached report and screenshots.',
    attachments: [
      {
        filename: 'playwright-report.html',
        path: path.join('./playwright-report/index.html'), // Path to the report generated by Playwright
      },
      {
        filename: 'screenshot.png', // Screenshot name
        path: path.join('./screenshots/screenshot.png'), // Path to your screenshot folder
      },
    ],
  };

  // Send email
  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent: ' + info.response);
  } catch (error) {
    console.log('Error sending email: ', error);
  }
};
